# Test description:
#   This test checks that if we set up a router with a globally configured max-tx-rate,
#   every participant forwards data at the max-tx-rate specified.
#
# Test architecture:
#                                      topic_0 5 Hz┌────────────┐
#                                   ┌──────────────►subscriber_1│
#                                   │              │            │
# ┌───────────┐             ┌───────┴─┐            │(local)     │
# │publisher_0│topic_0 10 Hz│ddsproxy│            └────────────┘
# │           ├─────────────►         │
# │(local)    │             │(local)  │            ┌────────────┐
# └───────────┘             └───────┬─┘            │subscriber_2│
#                                   │  topic_0 5 Hz│            │
#                                   └──────────────►(local)     │
#                                                  └────────────┘

services:

  # ROUTER
  ddsproxy:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsproxy
    networks:
      - std_net
    volumes:
      - ./ddsproxy.yaml:/config.yaml
    command: ddsproxy -c /config.yaml --timeout 8

  # DOMAIN 0
  publisher_0:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0
    networks:
      - std_net
    command: install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample publisher --interval 100 --samples 80 --domain 80 --topic topic_0

  # DOMAIN 1
  subscriber_1:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 81 --topic topic_0"

  # DOMAIN 2
  subscriber_2:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 82 --topic topic_0"

networks:
  std_net:
  default:
    driver: none
