# Test description:
#   This test checks that if we set up a router with any as the discovery trigger,
#   a subscriber does match with the router (since it triggers the creation of entities).
#
# Test architecture:
#
# ┌──────────┐    ┌─────────┐
# │subscriber│    │ddsproxy│
# │          ├────►         │
# │(local)   │    │(local)  │
# └──────────┘    └─────────┘

services:

  # ROUTER
  ddsproxy:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsproxy
    networks:
      - std_net
    volumes:
      - ../ddsproxy.yaml:/config.yaml
    command: ddsproxy -c /config.yaml --timeout 4

  # DOMAIN 0
  subscriber_0_t0:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_0_t0
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --n-matches 1 --timeout 4 --args "--domain 80"

networks:
  std_net:
  default:
    driver: none
