# Test description:
#   This test checks that tracks get deleted when their last subscriber disconnects.
#
# Test architecture:
#
# 1. Check that the subscriber receives the data sent by the publisher.
#
# ┌───────────────────┐             ┌────────────────────┐
# │  Domain 80        │             │         Domain 81  │
# │ ┌──────────────┐ ┌┼─────────────┼┐ ┌───────────────┐ │
# │ │publisher_0_t0│ ││  ddsproxy  ││ │subscriber_1_t0│ │
# │ │            ──┼─┼┤►           ─┼┼─┤►              │ │
# │ │(local)       │ ││  (local)    ││ │(local)        │ │
# │ └──────────────┘ └┼─────────────┼┘ └───────────────┘ │
# │                   │             │                    │
# └───────────────────┘             └────────────────────┘
#
# 2. Check that when the subscriber disconnects the track gets deleted.
#
# ┌───────────────────┐             ┌────────────────────┐
# │  Domain 80        │             │         Domain 81  │
# │ ┌──────────────┐ ┌┼─────────────┼┐                   │
# │ │publisher_0_t0│ ││  ddsproxy  ││                   │
# │ │              │ ││             ││                   │
# │ │(local)       │ ││  (local)    ││                   │
# │ └──────────────┘ └┼─────────────┼┘                   │
# │                   │             │                    │
# └───────────────────┘             └────────────────────┘
#

services:

  # ROUTER
  ddsproxy:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsproxy
    networks:
      - std_net
    volumes:
      - ./ddsproxy.yaml:/config.yaml
    command: ddsproxy -c /config.yaml --timeout 10


  # DOMAIN 80
  publisher_0_t0:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0_t0
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_publisher.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --n-unmatches 1 --timeout 8 --args "--samples 80 --domain 80 --topic topic0 --interval 100"


  # DOMAIN 81
  subscriber_1_t0:
    image: ${DDSPROXY_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1_t0
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 4 --args "--samples 20 --domain 81 --topic topic0"


networks:
  std_net:
  default:
    driver: none
